# Generated by Django 4.2.3 on 2023-07-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0002_soilnutrient_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilnutrient',
            name='created_by',
        ),
        migrations.AddField(
            model_name='soilnutrient',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soilnutrient',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soilnutrient',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='soilnutrient',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
