# Generated by Django 4.2.3 on 2023-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
